const demo=[
{id:'d1',start:0,end:4.2,en:'Morning, everyone. Shall we get started?',zh:'大家早上好，我们开始吧？',speaker:'女声 · Speaker A',practice:true,count:2},
{id:'d2',start:4.2,end:8.4,en:'Sure. I have a quick update on the project.',zh:'好的，我简单更新一下项目进展。',speaker:'男声 · Speaker B',practice:true,count:1},
{id:'d3',start:8.4,end:12.7,en:'We finished the first test yesterday.',zh:'我们昨天完成了第一次测试。',speaker:'男声 · Speaker B',practice:false,count:0},
{id:'d4',start:12.7,end:17.6,en:'That sounds good. Did you find any issues?',zh:'听起来不错。你们发现什么问题了吗？',speaker:'女声 · Speaker A',practice:true,count:0},
{id:'d5',start:17.6,end:22.8,en:'There are two small problems, but we can fix them today.',zh:'有两个小问题，不过我们今天可以解决。',speaker:'男声 · Speaker B',practice:true,count:0}
];
const $=id=>document.getElementById(id);let cues=structuredClone(demo),index=0,mode='shadowing',subtitleMode='both',loop=false,videoUrl='',demoTimer=null,lastStop='';
const video=$('video');
function seconds(v){const p=v.trim().replace(',','.').split(':').map(Number);return p.length===3?p[0]*3600+p[1]*60+p[2]:p.length===2?p[0]*60+p[1]:Number(v)||0}
function time(v){v=Math.max(0,v||0);return `${String(Math.floor(v/60)).padStart(2,'0')}:${String(Math.floor(v%60)).padStart(2,'0')}.${Math.floor(v%1*10)}`}
function parseSubtitles(text){const blocks=text.replace(/^WEBVTT[^\n]*\n/i,'').replace(/\r/g,'').trim().split(/\n{2,}/);return blocks.map((block,i)=>{const lines=block.split('\n').filter(Boolean),ti=lines.findIndex(l=>l.includes('-->'));if(ti<0)return null;const [a,b]=lines[ti].split('-->'),content=lines.slice(ti+1).map(l=>l.replace(/<[^>]+>/g,'').trim()).filter(Boolean);if(!content.length)return null;let speaker='Speaker',first=content[0],m=first.match(/^(?:\[([^\]]+)\]|([A-Za-z]+(?:\s+[A-Za-z])?)):\s*(.*)$/);if(m){speaker=m[1]||m[2];first=m[3]}const all=[first,...content.slice(1)],en=all.filter(l=>/[A-Za-z]/.test(l)).join(' ')||content[0],zh=content.filter(l=>/[\u3400-\u9fff]/.test(l)).join(' ');return{id:`c${Date.now()}-${i}`,start:seconds(a),end:seconds(b.trim().split(/\s+/)[0]),en,zh,speaker,practice:true,count:0}}).filter(Boolean).sort((a,b)=>a.start-b.start)}
function save(){localStorage.setItem('video-shadowing-v1',JSON.stringify({mode,subtitleMode,rate:video.playbackRate||1}));localStorage.setItem('video-shadowing-progress-v1',JSON.stringify(cues.map(({id,practice,count})=>({id,practice,count}))))}
function render(){const cue=cues[index];if(!cue)return;$('speaker').textContent=cue.speaker;$('english').textContent=cue.en;$('chinese').textContent=cue.zh;$('chinese').classList.toggle('hidden',subtitleMode!=='both'||!cue.zh);$('subtitleOverlay').classList.toggle('hidden',subtitleMode==='off');$('position').textContent=`${index+1} / ${cues.length}`;$('startTime').textContent=time(cue.start);$('endTime').textContent=time(cues.at(-1).end);$('progressBar').style.width=`${(index+1)/cues.length*100}%`;$('prevBtn').disabled=index===0;$('nextBtn').disabled=index===cues.length-1;$('sentenceTotal').textContent=`${cues.length} 句`;const selected=cues.filter(c=>c.practice).length,done=cues.filter(c=>c.count>0).length;$('practiceTotal').textContent=`${selected} 句需跟读`;$('selectedCount').textContent=selected;$('doneCount').textContent=done;$('completion').textContent=`${Math.round(done/Math.max(selected,1)*100)}%`;renderList();fillEditor()}
function renderList(){const q=$('searchInput').value.trim().toLowerCase();$('sentenceList').innerHTML='';cues.forEach((cue,i)=>{if(q&&!`${cue.en} ${cue.zh} ${cue.speaker}`.toLowerCase().includes(q))return;const item=document.createElement('article');item.className=`sentence-item ${i===index?'current':''}`;item.innerHTML=`<button class="check ${cue.practice?'checked':''}" aria-label="${cue.practice?'取消':'选择'}跟读本句">${cue.practice?'✓':''}</button><div class="copy"><div class="cue-meta"><b>${String(i+1).padStart(2,'0')}</b><span>${time(cue.start)}–${time(cue.end)}</span><em>${cue.speaker}</em></div><strong>${cue.en}</strong>${cue.zh?`<p>${cue.zh}</p>`:''}</div>${cue.count?`<span class="repeat">×${cue.count}</span>`:''}`;item.addEventListener('click',()=>seek(i));item.querySelector('.check').addEventListener('click',e=>{e.stopPropagation();cue.practice=!cue.practice;save();render()});$('sentenceList').append(item)})}
function seek(i,autoplay=false){index=Math.max(0,Math.min(i,cues.length-1));lastStop='';$('practicePrompt').classList.add('hidden');if(videoUrl){video.currentTime=cues[index].start+.01;if(autoplay)video.play()}render()}
function setPlaying(playing){$('stagePlay').textContent=$('playBtn').textContent=playing?'Ⅱ':'▶';$('stagePlay').ariaLabel=playing?'暂停':'播放'}
function playDemo(){setPlaying(true);clearTimeout(demoTimer);demoTimer=setTimeout(()=>{setPlaying(false);if(mode==='shadowing'&&cues[index].practice)$('practicePrompt').classList.remove('hidden');else if(index<cues.length-1)seek(index+1)},Math.max(900,Math.min(2600,(cues[index].end-cues[index].start)*420)))}
function togglePlay(){if(!videoUrl){playDemo();return}video.paused?video.play():video.pause()}
function complete(){cues[index].count++;save();index<cues.length-1?seek(index+1,!!videoUrl):$('practicePrompt').classList.add('hidden')}
function fillEditor(){const c=cues[index];$('editStart').value=c.start;$('editEnd').value=c.end;$('editSpeaker').value=c.speaker;$('editEnglish').value=c.en;$('editChinese').value=c.zh}
function updateField(key,value){cues[index][key]=value;save();render()}
video.addEventListener('play',()=>setPlaying(true));video.addEventListener('pause',()=>setPlaying(false));video.addEventListener('timeupdate',()=>{const t=video.currentTime,found=cues.findIndex((c,i)=>t>=c.start&&(t<c.end||i===cues.length-1));if(found>=0&&found!==index){index=found;lastStop='';render()}const cue=cues[found>=0?found:index];if(!cue||t<cue.end-.06)return;if(loop){video.currentTime=cue.start+.01;return}if(mode==='shadowing'&&cue.practice&&lastStop!==cue.id){lastStop=cue.id;video.pause();$('practicePrompt').classList.remove('hidden')}});
$('videoInput').addEventListener('change',e=>{const file=e.target.files[0];if(!file)return;if(videoUrl)URL.revokeObjectURL(videoUrl);videoUrl=URL.createObjectURL(file);video.src=videoUrl;$('videoStage').classList.add('has-video');$('projectName').textContent=file.name;$('notice').textContent='视频已在本机打开，不会上传到服务器。现在请导入对应字幕。';seek(0)});
$('subtitleInput').addEventListener('change',async e=>{const file=e.target.files[0];if(!file)return;const parsed=parseSubtitles(await file.text());if(!parsed.length){$('notice').textContent='没有识别到有效字幕，请确认文件为标准 SRT 或 VTT。';return}cues=parsed;index=0;$('subtitleName').textContent=file.name;$('notice').textContent=`已读取 ${cues.length} 句字幕，可以点击任意句检查时间。`;render()});
$('stagePlay').onclick=$('playBtn').onclick=togglePlay;$('prevBtn').onclick=()=>seek(index-1,!!videoUrl);$('nextBtn').onclick=()=>seek(index+1,!!videoUrl);$('repeatBtn').onclick=()=>seek(index,!!videoUrl);$('completeBtn').onclick=complete;$('loopBtn').onclick=()=>{loop=!loop;$('loopBtn').classList.toggle('active',loop)};
document.querySelectorAll('[data-mode]').forEach(b=>b.onclick=()=>{mode=b.dataset.mode;document.querySelectorAll('[data-mode]').forEach(x=>x.classList.toggle('active',x===b));$('practicePrompt').classList.add('hidden');save()});document.querySelectorAll('[data-subtitle]').forEach(b=>b.onclick=()=>{subtitleMode=b.dataset.subtitle;document.querySelectorAll('[data-subtitle]').forEach(x=>x.classList.toggle('active',x===b));save();render()});
$('rateSelect').onchange=e=>{video.playbackRate=Number(e.target.value);save()};$('searchInput').oninput=renderList;$('editBtn').onclick=()=>{$('editor').classList.toggle('hidden');fillEditor()};$('closeEditor').onclick=()=>$('editor').classList.add('hidden');$('editStart').onchange=e=>updateField('start',Number(e.target.value));$('editEnd').onchange=e=>updateField('end',Number(e.target.value));$('editSpeaker').oninput=e=>updateField('speaker',e.target.value);$('editEnglish').oninput=e=>updateField('en',e.target.value);$('editChinese').oninput=e=>updateField('zh',e.target.value);
try{const s=JSON.parse(localStorage.getItem('video-shadowing-v1')||'{}');mode=s.mode||mode;subtitleMode=s.subtitleMode||subtitleMode;video.playbackRate=s.rate||1;$('rateSelect').value=String(s.rate||1);document.querySelectorAll('[data-mode]').forEach(b=>b.classList.toggle('active',b.dataset.mode===mode));document.querySelectorAll('[data-subtitle]').forEach(b=>b.classList.toggle('active',b.dataset.subtitle===subtitleMode))}catch{}
if('serviceWorker'in navigator)window.addEventListener('load',()=>navigator.serviceWorker.register('sw.js'));render();
window.VideoShadowing={parseSubtitles,formatTime:time};
